// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hexes.sql

package database

import (
	"context"
)

const createHex = `-- name: CreateHex :one
INSERT INTO hexes(id, name, uses, attunement, intelligence, faith, description, acquired, cost, hex_type)
VALUES (
  gen_random_uuid(),
  $1, 
  $2, 
  $3, 
  $4, 
  $5, 
  $6, 
  $7, 
  $8, 
  $9
) 
RETURNING id, name, uses, attunement, intelligence, faith, description, acquired, cost, hex_type
`

type CreateHexParams struct {
	Name         string `json:"name"`
	Uses         string `json:"uses"`
	Attunement   int32  `json:"attunement"`
	Intelligence int32  `json:"intelligence"`
	Faith        int32  `json:"faith"`
	Description  string `json:"description"`
	Acquired     string `json:"acquired"`
	Cost         string `json:"cost"`
	HexType      string `json:"hex_type"`
}

func (q *Queries) CreateHex(ctx context.Context, arg CreateHexParams) (Hex, error) {
	row := q.db.QueryRowContext(ctx, createHex,
		arg.Name,
		arg.Uses,
		arg.Attunement,
		arg.Intelligence,
		arg.Faith,
		arg.Description,
		arg.Acquired,
		arg.Cost,
		arg.HexType,
	)
	var i Hex
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Uses,
		&i.Attunement,
		&i.Intelligence,
		&i.Faith,
		&i.Description,
		&i.Acquired,
		&i.Cost,
		&i.HexType,
	)
	return i, err
}

const getHexes = `-- name: GetHexes :many
SELECT id, name, uses, attunement, intelligence, faith, description, acquired, cost, hex_type FROM hexes
`

func (q *Queries) GetHexes(ctx context.Context) ([]Hex, error) {
	rows, err := q.db.QueryContext(ctx, getHexes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Hex
	for rows.Next() {
		var i Hex
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Uses,
			&i.Attunement,
			&i.Intelligence,
			&i.Faith,
			&i.Description,
			&i.Acquired,
			&i.Cost,
			&i.HexType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
