// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: miracles.sql

package database

import (
	"context"
)

const createMiracle = `-- name: CreateMiracle :one
INSERT INTO miracles (id, name, uses, attunement, description, acquired, cost, miracle_type)
VALUES (
  gen_random_uuid(),
  $1, 
  $2, 
  $3, 
  $4, 
  $5, 
  $6, 
  $7
) 
RETURNING id, name, uses, attunement, description, acquired, cost, miracle_type
`

type CreateMiracleParams struct {
	Name        string
	Uses        int32
	Attunement  int32
	Description string
	Acquired    string
	Cost        int32
	MiracleType string
}

func (q *Queries) CreateMiracle(ctx context.Context, arg CreateMiracleParams) (Miracle, error) {
	row := q.db.QueryRowContext(ctx, createMiracle,
		arg.Name,
		arg.Uses,
		arg.Attunement,
		arg.Description,
		arg.Acquired,
		arg.Cost,
		arg.MiracleType,
	)
	var i Miracle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Uses,
		&i.Attunement,
		&i.Description,
		&i.Acquired,
		&i.Cost,
		&i.MiracleType,
	)
	return i, err
}
