// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/google/uuid"
)

type Hex struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Uses         string    `json:"uses"`
	Attunement   int32     `json:"attunement"`
	Intelligence int32     `json:"intelligence"`
	Faith        int32     `json:"faith"`
	Description  string    `json:"description"`
	Acquired     string    `json:"acquired"`
	Cost         string    `json:"cost"`
	HexType      string    `json:"hex_type"`
}

type Miracle struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Uses        string    `json:"uses"`
	Attunement  int32     `json:"attunement"`
	Faith       int32     `json:"faith"`
	Description string    `json:"description"`
	Acquired    string    `json:"acquired"`
	MiracleType string    `json:"miracle_type"`
}

type Pyromancy struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	Uses          string    `json:"uses"`
	Attunement    int32     `json:"attunement"`
	Description   string    `json:"description"`
	Acquired      string    `json:"acquired"`
	Cost          string    `json:"cost"`
	PyromancyType string    `json:"pyromancy_type"`
}

type Sorcery struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Uses         string    `json:"uses"`
	Spellslot    int32     `json:"spellslot"`
	Intelligence int32     `json:"intelligence"`
	Description  string    `json:"description"`
	Acquired     string    `json:"acquired"`
	Cost         string    `json:"cost"`
	SorceryType  string    `json:"sorcery_type"`
}
