// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/google/uuid"
)

type Hex struct {
	ID           uuid.UUID
	Name         string
	Uses         int32
	Attunement   int32
	Intelligence int32
	Faith        int32
	Description  string
	Acquired     string
	Cost         int32
	HexType      string
}

type Miracle struct {
	ID          uuid.UUID
	Name        string
	Uses        int32
	Attunement  int32
	Description string
	Acquired    string
	Cost        int32
	MiracleType string
}

type Pyromancy struct {
	ID            uuid.UUID
	Name          string
	Uses          int32
	Attunement    int32
	Description   string
	Acquired      string
	Cost          int32
	PyromancyType string
}

type Sorcery struct {
	ID           uuid.UUID
	Name         string
	Uses         int32
	Spellslot    int32
	Intelligence int32
	Description  string
	Acquired     string
	Cost         int32
}
