// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pyromancies.sql

package database

import (
	"context"
)

const createPyromancy = `-- name: CreatePyromancy :one
INSERT INTO pyromancies(id, name, uses, attunement, description, acquired, cost, pyromancy_type)
VALUES (
  gen_random_uuid(), 
  $1, 
  $2, 
  $3, 
  $4, 
  $5, 
  $6, 
  $7
)
RETURNING id, name, uses, attunement, description, acquired, cost, pyromancy_type
`

type CreatePyromancyParams struct {
	Name          string
	Uses          int32
	Attunement    int32
	Description   string
	Acquired      string
	Cost          int32
	PyromancyType string
}

func (q *Queries) CreatePyromancy(ctx context.Context, arg CreatePyromancyParams) (Pyromancy, error) {
	row := q.db.QueryRowContext(ctx, createPyromancy,
		arg.Name,
		arg.Uses,
		arg.Attunement,
		arg.Description,
		arg.Acquired,
		arg.Cost,
		arg.PyromancyType,
	)
	var i Pyromancy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Uses,
		&i.Attunement,
		&i.Description,
		&i.Acquired,
		&i.Cost,
		&i.PyromancyType,
	)
	return i, err
}
