// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pyromancies.sql

package database

import (
	"context"
)

const createPyromancy = `-- name: CreatePyromancy :one
INSERT INTO pyromancies(id, name, uses, attunement, description, acquired, cost, pyromancy_type)
VALUES (
  gen_random_uuid(), 
  $1, 
  $2, 
  $3, 
  $4, 
  $5, 
  $6, 
  $7
)
RETURNING id, name, uses, attunement, description, acquired, cost, pyromancy_type
`

type CreatePyromancyParams struct {
	Name          string `json:"name"`
	Uses          string `json:"uses"`
	Attunement    int32  `json:"attunement"`
	Description   string `json:"description"`
	Acquired      string `json:"acquired"`
	Cost          string `json:"cost"`
	PyromancyType string `json:"pyromancy_type"`
}

func (q *Queries) CreatePyromancy(ctx context.Context, arg CreatePyromancyParams) (Pyromancy, error) {
	row := q.db.QueryRowContext(ctx, createPyromancy,
		arg.Name,
		arg.Uses,
		arg.Attunement,
		arg.Description,
		arg.Acquired,
		arg.Cost,
		arg.PyromancyType,
	)
	var i Pyromancy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Uses,
		&i.Attunement,
		&i.Description,
		&i.Acquired,
		&i.Cost,
		&i.PyromancyType,
	)
	return i, err
}

const getPyromancies = `-- name: GetPyromancies :many
SELECT id, name, uses, attunement, description, acquired, cost, pyromancy_type FROM pyromancies
`

func (q *Queries) GetPyromancies(ctx context.Context) ([]Pyromancy, error) {
	rows, err := q.db.QueryContext(ctx, getPyromancies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pyromancy
	for rows.Next() {
		var i Pyromancy
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Uses,
			&i.Attunement,
			&i.Description,
			&i.Acquired,
			&i.Cost,
			&i.PyromancyType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
