// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sorceries.sql

package database

import (
	"context"
)

const createSorcery = `-- name: CreateSorcery :one
INSERT INTO sorceries(id, name, uses, spellslot, intelligence, description, acquired, cost)
VALUES(
  gen_random_uuid(),
  $1, 
  $2, 
  $3, 
  $4,
  $5, 
  $6, 
  $7
)
RETURNING id, name, uses, spellslot, intelligence, description, acquired, cost
`

type CreateSorceryParams struct {
	Name         string
	Uses         int32
	Spellslot    int32
	Intelligence int32
	Description  string
	Acquired     string
	Cost         int32
}

func (q *Queries) CreateSorcery(ctx context.Context, arg CreateSorceryParams) (Sorcery, error) {
	row := q.db.QueryRowContext(ctx, createSorcery,
		arg.Name,
		arg.Uses,
		arg.Spellslot,
		arg.Intelligence,
		arg.Description,
		arg.Acquired,
		arg.Cost,
	)
	var i Sorcery
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Uses,
		&i.Spellslot,
		&i.Intelligence,
		&i.Description,
		&i.Acquired,
		&i.Cost,
	)
	return i, err
}
