// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sorceries.sql

package database

import (
	"context"
)

const createSorcery = `-- name: CreateSorcery :one
INSERT INTO sorceries(id, name, uses, spellslot, intelligence, description, acquired, cost, sorcery_type)
VALUES(
  gen_random_uuid(),
  $1, 
  $2, 
  $3, 
  $4,
  $5, 
  $6, 
  $7,
  $8
)
RETURNING id, name, uses, spellslot, intelligence, description, acquired, cost, sorcery_type
`

type CreateSorceryParams struct {
	Name         string `json:"name"`
	Uses         string `json:"uses"`
	Spellslot    int32  `json:"spellslot"`
	Intelligence int32  `json:"intelligence"`
	Description  string `json:"description"`
	Acquired     string `json:"acquired"`
	Cost         string `json:"cost"`
	SorceryType  string `json:"sorcery_type"`
}

func (q *Queries) CreateSorcery(ctx context.Context, arg CreateSorceryParams) (Sorcery, error) {
	row := q.db.QueryRowContext(ctx, createSorcery,
		arg.Name,
		arg.Uses,
		arg.Spellslot,
		arg.Intelligence,
		arg.Description,
		arg.Acquired,
		arg.Cost,
		arg.SorceryType,
	)
	var i Sorcery
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Uses,
		&i.Spellslot,
		&i.Intelligence,
		&i.Description,
		&i.Acquired,
		&i.Cost,
		&i.SorceryType,
	)
	return i, err
}

const getSorceries = `-- name: GetSorceries :many
SELECT id, name, uses, spellslot, intelligence, description, acquired, cost, sorcery_type FROM sorceries
`

func (q *Queries) GetSorceries(ctx context.Context) ([]Sorcery, error) {
	rows, err := q.db.QueryContext(ctx, getSorceries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sorcery
	for rows.Next() {
		var i Sorcery
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Uses,
			&i.Spellslot,
			&i.Intelligence,
			&i.Description,
			&i.Acquired,
			&i.Cost,
			&i.SorceryType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
